export default {
  login: 'mishafrenkel',
  id: 18464282,
  node_id: 'MDQ6VXNlcjE4NDY0Mjgy',
  avatar_url: 'https://avatars0.githubusercontent.com/u/18464282?v=4',
  gravatar_id: '',
  url: 'https://avatars.githubusercontent.com/mishafrenkel',
  html_url: 'https://github.com/mishafrenkel',
  followers_url: 'https://api.github.com/users/mishafrenkel/followers',
  following_url: 'https://api.github.com/users/mishafrenkel/following{/other_user}',
  gists_url: 'https://api.github.com/users/mishafrenkel/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/mishafrenkel/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/mishafrenkel/subscriptions',
  organizations_url: 'https://api.github.com/users/mishafrenkel/orgs',
  repos_url: 'https://api.github.com/users/mishafrenkel/repos',
  events_url: 'https://api.github.com/users/mishafrenkel/events{/privacy}',
  received_events_url: 'https://api.github.com/users/mishafrenkel/received_events',
  type: 'User',
  site_admin: false,
  name: 'Michael Frenkel',
  company: 'Independant Contractor ',
  blog: 'https://mikefrenkel.com/',
  location: 'San Francisco',
  email: null,
  hireable: true,
  bio: null,
  public_repos: 72,
  public_gists: 4,
  followers: 248,
  following: 12,
  created_at: '2016-04-14T13:19:00Z',
  updated_at: '2019-10-25T02:04:53Z',
};
